allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  de16356f-5973-4d49-982a-bf6c50ef13ce:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-03-14T15:47:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 250e82a8-902d-4619-9ddf-386ec1318f8f
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 166709ab-a923-49af-8785-7c40c8100fc3
        userCondition: null
    thumbFieldKey: null
handle: category
hasTitleField: true
icon: null
name: Categorie
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
