allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  9609c058-70c7-4152-b0ba-dc3c9c612180:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-05-14T05:51:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9907fcca-19e3-4136-b5a6-82353815cb6b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e41cf0f2-5b73-42d5-a554-cdfb5262b16f
        userCondition: null
    thumbFieldKey: null
handle: contactPage
hasTitleField: true
icon: null
name: 'Contact page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
