allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  9d858e91-3d51-43c0-9983-bbefffbdbf33:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-03-14T12:46:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d7ac968f-74ef-42b0-9d3a-65a09f2ca385
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-14T19:02:13+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c44b51c5-f987-4977-9704-1f0a919c3bac # Content Builder
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f01d9bd-a3e5-4881-9797-6d64ec3b02f6
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: ae04c552-a2dc-43ce-8ccf-d0352b0d783d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-05-13T19:27:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f74da79a-8274-49ce-b7aa-81bd4d5abe9e # Text
            handle: overviewTitle
            instructions: null
            label: 'Overview title'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84a28d39-52fd-4bf1-901d-1b1f9ca547e2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-13T19:27:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c7f8a940-f9bd-49be-b008-4941e4372bc0 # Rich Text - Simple
            handle: overviewDescription
            instructions: null
            label: 'Overview description'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac04f5c8-5019-41ba-8424-d33977d33d60
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-05-13T19:27:15+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 07d5b138-2a5f-4e1d-94fb-ea4451ce830a # Image
            handle: overviewImage
            instructions: null
            label: 'Overview image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eb1ffb78-bea0-4bdf-86ba-1405fb33a52c
            userCondition: null
            warning: null
            width: 100
        name: Overview
        uid: be9f8e6a-28c9-488f-aec5-bed1a5145c2e
        userCondition: null
    thumbFieldKey: null
handle: page
hasTitleField: true
icon: null
name: 'Contentbuilder Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
